// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raqkxeahwupzhuyfnsew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhcWt4ZWFod3Vwemh1eWZuc2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Nzc2MDMsImV4cCI6MjA2OTM1MzYwM30.l3Q49LHVb33NdV_ufH204UWliyp7dRrcC7xO4orzP_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});